### ISSUE TITLE
Final Week Check-list

### ISSUE THREAD

**Issue by Lucca-Sidey** [Ednormous/CITS3403-Group-Project#23]
- [x] Logic for nested replies on message board- Lucca
- [x] Search Bar - Wes
- [x] Time Table - Josh
- [ ] Contact page finishing styling and details - Josh
- [x] Security Logic
- [x] edit the login security (use wtfform instead)
- [x] Migration of updated db - Lucca
- [x] Tests
- [x] Create Blueprint.py/ change routes
- [x] homepage designs
- [x] admin page finalisation (add a section to enrol users to classes; add/delete classes)
- [ ] ....... add your name and anything else to the check list.

**Comment by wdATuwa** [comment]
blueprints is for allows the routes/test envi to be set.
