### ISSUE TITLE
To be finalised - README.md

### ISSUE THREAD

**Issue by Ednormous** [Ednormous/CITS3403-Group-Project#37]
@Lucca-Sidey 

Before zipping all the source code, make sure to finalise the README.md file. There is still a small section to finish in there. Might want to add some more details for how the app is ran.

@wdATuwa @Josh-Trainer 

I've read through some of the code, and some features were not yet implemented. You may want to remove these code to make the code appear cleaner. 

Thanks mate!

**Comment by wdATuwa** [comment]
All finished, thanks for everybody's help.
